services:
  frontend:
    container_name: frontend
    environment:
      - HUSKY=0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  
  node_backend:
    image: node:20
    container_name: node_backend
    working_dir: /node_backend
    command: sh -c "npm install && npx sequelize-cli db:migrate --config ./configs/config.js && npm run start-backend"
    ports:
      - "3000:443"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/node_backend
      - ./backend/certs:/node_backend/certs
  llm-backend:
    build: llm_backend
    container_name: llm_backend
    image: "python:3.11-slim"
    ports:
      - "5001:5001"
    env_file:
      - ./llm_backend/.env
    volumes:
      - ./llm_backend:/llm_backend
    depends_on:
      - node_backend
    working_dir: /llm_backend
    command: >
      sh -c "apt-get update && apt-get install -y ffmpeg && pip install --no-cache-dir -r ./requirements.txt && python main.py"
  db:
    image: postgres:15
    container_name: postgres_db
    env_file: "./backend/.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  clamav:
    platform: linux/x86_64 # uncomment this line if you are using mac
    image: clamav/clamav:latest
    container_name: clamav
    volumes:
      - ./clamav/database:/var/lib/clamav
      - ./backend/uploads:/uploads
      - ./clamav/configs:/etc/clamav
    ports:
      - "3310:3310"
    command: > 
      sh -c "freshclam -d & clamd"
volumes:
  postgres-data:
