services:
  node_backend:
    image: node:20
    working_dir: /app
    command: sh -c "npm install && npm run start-backend"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
  llm-backend:
    build: llm_backend
    container_name: llm_backend
    image: "python:3.11-slim"
    ports:
      - "5001:5001"
    env_file:
      - ./llm_backend/.env
    volumes:
      - ./:/llm_backend
    working_dir: /llm_backend
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python main.py"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  
