/* tslint:disable */
/* eslint-disable */
/**
 * Oculavis Arcanum API
 * The Oculavis Arcanum API allows you to manage cases by creating, retrieving, updating, and deleting them. It also supports file attachments associated with cases. The API also includes endpoints for managing chat functionality, including creating, retrieving, updating, and exporting chat sessions and messages. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

