openapi: 3.1.0
info:
  title: Oculavis Arcanum API
  description: |
    The Oculavis Arcanum API allows you to manage cases by creating, retrieving, updating, and deleting them. It also supports file attachments associated with cases.
  version: '1.0.0'
servers:
  - url: http://localhost:3000/api
paths:
  /cases:
    get:
      summary: Retrieve all cases
      description: Retrieve a list of all cases.
      responses:
        200:
          description: Successfully retrieved a list of cases.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
        500:
          description: Error retrieving cases.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new case
      description: Create a new case.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CasePost'
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Attached files on upload.
      responses:
        201:
          description: Case successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        400:
          description: Validation error or file upload error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error creating the case.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cases/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Unique identifier of the case.
        schema:
          type: integer
    get:
      summary: Retrieve a case by ID
      description: Retrieve a specific case by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case to retrieve.
          schema:
            type: integer
      responses:
        200:
          description: Successfully retrieved the case.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        404:
          description: Case not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error retrieving the case.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a case by ID
      description: Update an existing case by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CasePut'
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Attached files on upload.
      responses:
        200:
          description: Case successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        404:
          description: Case with specified ID not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error updating the case.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            multipart/form-data:
              schema:
                type: object
                properties:
                  filename:
                    type: array
                    items:
                      type: string
                      format: binary
    delete:
      summary: Delete a case by ID
      description: Delete a specific case by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case to delete.
          schema:
            type: integer
      responses:
        204:
          description: Case successfully deleted.
        404:
          description: Case with specified ID not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error deleting the case.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cases/{id}/attachments:
    post:
      summary: Upload attachments for a case
      description: Upload one or more files as attachments for a specific case.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case to which the files will be attached.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Files to upload.
      responses:
        200:
          description: Files successfully uploaded and associated with the case.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID of the case.
                  uploadedFiles:
                    type: array
                    items:
                      type: string
                      description: List of successfully uploaded file names.
        400:
          description: Validation error or unsupported file type.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error uploading the files.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cases/{id}/attachments/{filename}:
    get:
      summary: Download an attachment
      description: Download an attachment associated with a case.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case.
          schema:
            type: integer
        - name: filename
          in: path
          required: true
          description: Name of the attachment file.
          schema:
            type: string
      responses:
        200:
          description: File successfully downloaded.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        404:
          description: Case or attachment not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Error downloading the attachment.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /createCaseFromFiles:
    post:
      summary: Create cases from uploaded files.
      description: Upload files, process them, and create draft cases.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Files to be uploaded.
                socket_id:
                  type: integer
                  description: Socket ID for real-time communication.
      responses:
        '201':
          description: Cases created successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
        '400':
          description: Bad request, invalid file upload or input.
        '500':
          description: Server error during file processing or case creation.
  /confirmCase/{id}:
    put:
      summary: Confirm and update a draft case.
      description: Update a draft case with additional details and mark it as confirmed.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the case to confirm.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CasePut'
      responses:
        '200':
          description: Case updated and confirmed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        '404':
          description: Case not found.
        '500':
          description: Server error during case update.
components:
  schemas:
    Case:
      allOf:
        - $ref: '#/components/schemas/CasePost'
      type: object
      required: [id, draft, createdAt, updatedAt, attachments]
      properties:
        id:
          type: integer
        draft:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        attachments:
          type: array
          description: List of attachments associated with the case.
          items:
            type: object
            properties:
              id:
                type: integer
              filename:
                type: string
              filepath:
                type: string

    CasePost:
      allOf:
        - $ref: '#/components/schemas/CasePut'

    CasePut:
      type: object
      required: [title, description]
      properties:
        title:
          type: string
          description: Title of the case.
        description:
          type: string
          description: Description of the case.
        solution:
          type: string
          description: Solution for the case.
        assignee:
          type: string
          description: Person responsible for the case.
        status:
          type: string
          description: Status of the case.
          enum: [Open, In Progress, Solved, Closed]
        case_type:
          type: string
          description: Type of the case.
          enum: [Problem, Incident, Change, FAQ]
        priority:
          type: string
          description: Priority level of the case.
          enum: [Low, Medium, High]
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message.
        code:
          type: integer
          description: HTTP status code for the error.
