name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js Setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Install Backend Dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 4. Linting
      - name: Run Linting
        run: |
          cd backend
          npm run lint

      # 5. Testing
      - name: Run Tests
        run: |
          cd backend
          npm test
