name: LLM CI Pipeline
on:
  push:
    branches:
      - "issue/**"
      - "feature/**"
    paths:
      - 'llm_backend/**'
      - '.github/workflows/llm_ci.yml'
  pull_request:
    branches:
      - development
    paths:
      - 'llm_backend/**'
      - '.github/workflows/ci.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linter (flake8)
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39

      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true